# codecov.yml
coverage:
  status:
    project:
      default:
        # Require overall project coverage to stay at least the same
        target: auto
        threshold: 1% # allow small fluctuations
        informational: false
    patch:
      default:
        # Require changed lines in PRs to be covered
        target: auto
        threshold: 0%
        informational: false

comment:
  layout: 'diff, files'
  behavior: default
  require_changes: true # only comment when coverage changes
  hide_project_coverage: false

ignore:
  - 'src/__tests__/**'
  - '**/*.test.tsx'
  - '**/*.test.ts'
  - '**/*.spec.tsx'
  - '**/*.spec.ts'

# Flags are useful if you want separate coverage for frontend/backend later
flags:
  frontend:
    paths:
      - src/
